### ISSUE TITLE
file "EqpSingleton.h" is missing

### ISSUE THREAD

**Issue by kvnbautista** [tooniz/BillsBuddy#1]
Sorry to interrupt but do you have the 3 files that are missing and looks like those files are dependent for BBVariableStore and BBMethodStore to run smoothly. Thanks
"EqpSingleton.h"
"EqpSingleton.m"
"EqpUtilityDefines.h"

**Comment by tooniz** [comment]
https://github.com/tooniz/BillsBuddy/commit/0a40eb2f1377d5979b28144be2ccdfca19f915e1

Thanks, I added those files which were outside the project workspace
